export const chars = [
  { code: '&quot;', value: '"' },
  { code: '&amp;', value: '&' },
  { code: '&lt;', value: '<' },
  { code: '&gt;', value: '>' },
  { code: '&nbsp;', value: ' ' },
  { code: '&iexcl;', value: '¡' },
  { code: '&cent;', value: '¢' },
  { code: '&pound;', value: '£' },
  { code: '&curren;', value: '¤' },
  { code: '&yen;', value: '¥' },
  { code: '&brvbar;', value: '¦' },
  { code: '&sect;', value: '§' },
  { code: '&uml;', value: '¨' },
  { code: '&copy;', value: '©' },
  { code: '&ordf;', value: 'ª' },
  { code: '&laquo;', value: '«' },
  { code: '&not;', value: '¬' },
  { code: '&shy;', value: '­' },
  { code: '&reg;', value: '®' },
  { code: '&macr;', value: '¯' },
  { code: '&deg;', value: '°' },
  { code: '&plusmn;', value: '±' },
  { code: '&sup2;', value: '²' },
  { code: '&sup3;', value: '³' },
  { code: '&acute;', value: '´' },
  { code: '&micro;', value: 'µ' },
  { code: '&para;', value: '¶' },
  { code: '&middot;', value: '·' },
  { code: '&cedil;', value: '¸' },
  { code: '&sup1;', value: '¹' },
  { code: '&ordm;', value: 'º' },
  { code: '&raquo;', value: '»' },
  { code: '&frac14;', value: '¼' },
  { code: '&frac12;', value: '½' },
  { code: '&frac34;', value: '¾' },
  { code: '&iquest;', value: '¿' },
  { code: '&Agrave;', value: 'À' },
  { code: '&Aacute;', value: 'Á' },
  { code: '&Acirc;', value: 'Â' },
  { code: '&Atilde;', value: 'Ã' },
  { code: '&Auml;', value: 'Ä' },
  { code: '&Aring;', value: 'Å' },
  { code: '&AElig;', value: 'Æ' },
  { code: '&Ccedil;', value: 'Ç' },
  { code: '&Egrave;', value: 'È' },
  { code: '&Eacute;', value: 'É' },
  { code: '&Ecirc;', value: 'Ê' },
  { code: '&Euml;', value: 'Ë' },
  { code: '&Igrave;', value: 'Ì' },
  { code: '&Iacute;', value: 'Í' },
  { code: '&Icirc;', value: 'Î' },
  { code: '&Iuml;', value: 'Ï' },
  { code: '&ETH;', value: 'Ð' },
  { code: '&Ntilde;', value: 'Ñ' },
  { code: '&Ograve;', value: 'Ò' },
  { code: '&Oacute;', value: 'Ó' },
  { code: '&Ocirc;', value: 'Ô' },
  { code: '&Otilde;', value: 'Õ' },
  { code: '&Ouml;', value: 'Ö' },
  { code: '&times;', value: '×' },
  { code: '&Oslash;', value: 'Ø' },
  { code: '&Ugrave;', value: 'Ù' },
  { code: '&Uacute;', value: 'Ú' },
  { code: '&Ucirc;', value: 'Û' },
  { code: '&Uuml;', value: 'Ü' },
  { code: '&Yacute;', value: 'Ý' },
  { code: '&THORN;', value: 'Þ' },
  { code: '&szlig;', value: 'ß' },
  { code: '&agrave;', value: 'à' },
  { code: '&aacute;', value: 'á' },
  { code: '&acirc;', value: 'â' },
  { code: '&atilde;', value: 'ã' },
  { code: '&auml;', value: 'ä' },
  { code: '&aring;', value: 'å' },
  { code: '&aelig;', value: 'æ' },
  { code: '&ccedil;', value: 'ç' },
  { code: '&egrave;', value: 'è' },
  { code: '&eacute;', value: 'é' },
  { code: '&ecirc;', value: 'ê' },
  { code: '&euml;', value: 'ë' },
  { code: '&igrave;', value: 'ì' },
  { code: '&iacute;', value: 'í' },
  { code: '&icirc;', value: 'î' },
  { code: '&iuml;', value: 'ï' },
  { code: '&eth;', value: 'ð' },
  { code: '&ntilde;', value: 'ñ' },
  { code: '&ograve;', value: 'ò' },
  { code: '&oacute;', value: 'ó' },
  { code: '&ocirc;', value: 'ô' },
  { code: '&otilde;', value: 'õ' },
  { code: '&ouml;', value: 'ö' },
  { code: '&divide;', value: '÷' },
  { code: '&oslash;', value: 'ø' },
  { code: '&ugrave;', value: 'ù' },
  { code: '&uacute;', value: 'ú' },
  { code: '&ucirc;', value: 'û' },
  { code: '&uuml;', value: 'ü' },
  { code: '&yacute;', value: 'ý' },
  { code: '&thorn;', value: 'þ' },
  { code: '&yuml;', value: 'ÿ' },
  { code: '&#035;', value: '#' },
  { code: '&#036;', value: '$' },
  { code: '&#037;', value: '%' },
  { code: '&#038;', value: '&' },
  { code: '&#039;', value: '\'' },
  { code: '&#040;', value: '(' },
  { code: '&#041;', value: ')' },
  { code: '&#042;', value: '*' },
  { code: '&#043;', value: '#ERROR!' },
  { code: '&#044;', value: ',' },
  { code: '&#045;', value: '-' },
  { code: '&#046;', value: '.' },
  { code: '&#047;', value: '/' },
  { code: '&#048;', value: '0' },
  { code: '&#049;', value: '1' },
  { code: '&#050;', value: '2' },
  { code: '&#051;', value: '3' },
  { code: '&#052;', value: '4' },
  { code: '&#053;', value: '5' },
  { code: '&#054;', value: '6' },
  { code: '&#055;', value: '7' },
  { code: '&#056;', value: '8' },
  { code: '&#057;', value: '9' },
  { code: '&#058;', value: ':' },
  { code: '&#059;', value: ';' },
  { code: '&#060;', value: '<' },
  { code: '&#061;', value: '#ERROR!' },
  { code: '&#062;', value: '>' },
  { code: '&#063;', value: '?' },
  { code: '&#064;', value: '@' },
  { code: '&#065;', value: 'A' },
  { code: '&#066;', value: 'B' },
  { code: '&#067;', value: 'C' },
  { code: '&#068;', value: 'D' },
  { code: '&#069;', value: 'E' },
  { code: '&#070;', value: 'F' },
  { code: '&#071;', value: 'G' },
  { code: '&#072;', value: 'H' },
  { code: '&#073;', value: 'I' },
  { code: '&#074;', value: 'J' },
  { code: '&#075;', value: 'K' },
  { code: '&#076;', value: 'L' },
  { code: '&#077;', value: 'M' },
  { code: '&#078;', value: 'N' },
  { code: '&#079;', value: 'O' },
  { code: '&#080;', value: 'P' },
  { code: '&#081;', value: 'Q' },
  { code: '&#082;', value: 'R' },
  { code: '&#083;', value: 'S' },
  { code: '&#084;', value: 'T' },
  { code: '&#085;', value: 'U' },
  { code: '&#086;', value: 'V' },
  { code: '&#087;', value: 'W' },
  { code: '&#088;', value: 'X' },
  { code: '&#089;', value: 'Y' },
  { code: '&#090;', value: 'Z' },
  { code: '&#091;', value: '[' },
  { code: '&#092;', value: '\\' },
  { code: '&#093;', value: ']' },
  { code: '&#094;', value: '^' },
  { code: '&#095;', value: '_' },
  { code: '&#096;', value: '`' },
  { code: '&#097;', value: 'a' },
  { code: '&#098;', value: 'b' },
  { code: '&#099;', value: 'c' },
  { code: '&#100;', value: 'd' },
  { code: '&#101;', value: 'e' },
  { code: '&#102;', value: 'f' },
  { code: '&#103;', value: 'g' },
  { code: '&#104;', value: 'h' },
  { code: '&#105;', value: 'i' },
  { code: '&#106;', value: 'j' },
  { code: '&#107;', value: 'k' },
  { code: '&#108;', value: 'l' },
  { code: '&#109;', value: 'm' },
  { code: '&#110;', value: 'n' },
  { code: '&#111;', value: 'o' },
  { code: '&#112;', value: 'p' },
  { code: '&#113;', value: 'q' },
  { code: '&#114;', value: 'r' },
  { code: '&#115;', value: 's' },
  { code: '&#116;', value: 't' },
  { code: '&#117;', value: 'u' },
  { code: '&#118;', value: 'v' },
  { code: '&#119;', value: 'w' },
  { code: '&#120;', value: 'x' },
  { code: '&#121;', value: 'y' },
  { code: '&#122;', value: 'z' },
  { code: '&#123;', value: '{' },
  { code: '&#124;', value: '|' },
  { code: '&#125;', value: '}' },
  { code: '&#126;', value: '~' },
  { code: '&#160;', value: ' ' },
  { code: '&#161;', value: '¡' },
  { code: '&#162;', value: '¢' },
  { code: '&#163;', value: '£' },
  { code: '&#164;', value: '¤' },
  { code: '&#165;', value: '¥' },
  { code: '&#166;', value: '¦' },
  { code: '&#167;', value: '§' },
  { code: '&#168;', value: '¨' },
  { code: '&#169;', value: '©' },
  { code: '&#170;', value: 'ª' },
  { code: '&#171;', value: '«' },
  { code: '&#172;', value: '¬' },
  { code: '&#173;', value: '­' },
  { code: '&#174;', value: '®' },
  { code: '&#175;', value: '¯' },
  { code: '&#176;', value: '°' },
  { code: '&#177;', value: '±' },
  { code: '&#178;', value: '²' },
  { code: '&#179;', value: '³' },
  { code: '&#180;', value: '´' },
  { code: '&#181;', value: 'µ' },
  { code: '&#182;', value: '¶' },
  { code: '&#183;', value: '·' },
  { code: '&#184;', value: '¸' },
  { code: '&#185;', value: '¹' },
  { code: '&#186;', value: 'º' },
  { code: '&#187;', value: '»' },
  { code: '&#188;', value: '¼' },
  { code: '&#189;', value: '½' },
  { code: '&#190;', value: '¾' },
  { code: '&#191;', value: '¿' },
  { code: '&#192;', value: 'À' },
  { code: '&#193;', value: 'Á' },
  { code: '&#194;', value: 'Â' },
  { code: '&#195;', value: 'Ã' },
  { code: '&#196;', value: 'Ä' },
  { code: '&#197;', value: 'Å' },
  { code: '&#198;', value: 'Æ' },
  { code: '&#199;', value: 'Ç' },
  { code: '&#200;', value: 'È' },
  { code: '&#201;', value: 'É' },
  { code: '&#202;', value: 'Ê' },
  { code: '&#203;', value: 'Ë' },
  { code: '&#204;', value: 'Ì' },
  { code: '&#205;', value: 'Í' },
  { code: '&#206;', value: 'Î' },
  { code: '&#207;', value: 'Ï' },
  { code: '&#208;', value: 'Ð' },
  { code: '&#209;', value: 'Ñ' },
  { code: '&#210;', value: 'Ò' },
  { code: '&#211;', value: 'Ó' },
  { code: '&#212;', value: 'Ô' },
  { code: '&#213;', value: 'Õ' },
  { code: '&#214;', value: 'Ö' },
  { code: '&#215;', value: '×' },
  { code: '&#216;', value: 'Ø' },
  { code: '&#217;', value: 'Ù' },
  { code: '&#218;', value: 'Ú' },
  { code: '&#219;', value: 'Û' },
  { code: '&#220;', value: 'Ü' },
  { code: '&#221;', value: 'Ý' },
  { code: '&#222;', value: 'Þ' },
  { code: '&#223;', value: 'ß' },
  { code: '&#224;', value: 'à' },
  { code: '&#225;', value: 'á' },
  { code: '&#226;', value: 'â' },
  { code: '&#227;', value: 'ã' },
  { code: '&#228;', value: 'ä' },
  { code: '&#229;', value: 'å' },
  { code: '&#230;', value: 'æ' },
  { code: '&#231;', value: 'ç' },
  { code: '&#232;', value: 'è' },
  { code: '&#233;', value: 'é' },
  { code: '&#234;', value: 'ê' },
  { code: '&#235;', value: 'ë' },
  { code: '&#236;', value: 'ì' },
  { code: '&#237;', value: 'í' },
  { code: '&#238;', value: 'î' },
  { code: '&#239;', value: 'ï' },
  { code: '&#240;', value: 'ð' },
  { code: '&#241;', value: 'ñ' },
  { code: '&#242;', value: 'ò' },
  { code: '&#243;', value: 'ó' },
  { code: '&#244;', value: 'ô' },
  { code: '&#245;', value: 'õ' },
  { code: '&#246;', value: 'ö' },
  { code: '&#247;', value: '÷' },
  { code: '&#248;', value: 'ø' },
  { code: '&#249;', value: 'ù' },
  { code: '&#250;', value: 'ú' },
  { code: '&#251;', value: 'û' },
  { code: '&#252;', value: 'ü' },
  { code: '&#253;', value: 'ý' },
  { code: '&#254;', value: 'þ' },
  { code: '&#255;', value: 'ÿ' },
];
export const charss = [
  { '&quot;': '"' },
  { '&amp;': '&' },
  { '&lt;': '<' },
  { '&gt;': '>' },
  { '&nbsp;': ' ' },
  { '&iexcl;': '¡' },
  { '&cent;': '¢' },
  { '&pound;': '£' },
  { '&curren;': '¤' },
  { '&yen;': '¥' },
  { '&brvbar;': '¦' },
  { '&sect;': '§' },
  { '&uml;': '¨' },
  { '&copy;': '©' },
  { '&ordf;': 'ª' },
  { '&laquo;': '«' },
  { '&not;': '¬' },
  { '&shy;': '­' },
  { '&reg;': '®' },
  { '&macr;': '¯' },
  { '&deg;': '°' },
  { '&plusmn;': '±' },
  { '&sup2;': '²' },
  { '&sup3;': '³' },
  { '&acute;': '´' },
  { '&micro;': 'µ' },
  { '&para;': '¶' },
  { '&middot;': '·' },
  { '&cedil;': '¸' },
  { '&sup1;': '¹' },
  { '&ordm;': 'º' },
  { '&raquo;': '»' },
  { '&frac14;': '¼' },
  { '&frac12;': '½' },
  { '&frac34;': '¾' },
  { '&iquest;': '¿' },
  { '&Agrave;': 'À' },
  { '&Aacute;': 'Á' },
  { '&Acirc;': 'Â' },
  { '&Atilde;': 'Ã' },
  { '&Auml;': 'Ä' },
  { '&Aring;': 'Å' },
  { '&AElig;': 'Æ' },
  { '&Ccedil;': 'Ç' },
  { '&Egrave;': 'È' },
  { '&Eacute;': 'É' },
  { '&Ecirc;': 'Ê' },
  { '&Euml;': 'Ë' },
  { '&Igrave;': 'Ì' },
  { '&Iacute;': 'Í' },
  { '&Icirc;': 'Î' },
  { '&Iuml;': 'Ï' },
  { '&ETH;': 'Ð' },
  { '&Ntilde;': 'Ñ' },
  { '&Ograve;': 'Ò' },
  { '&Oacute;': 'Ó' },
  { '&Ocirc;': 'Ô' },
  { '&Otilde;': 'Õ' },
  { '&Ouml;': 'Ö' },
  { '&times;': '×' },
  { '&Oslash;': 'Ø' },
  { '&Ugrave;': 'Ù' },
  { '&Uacute;': 'Ú' },
  { '&Ucirc;': 'Û' },
  { '&Uuml;': 'Ü' },
  { '&Yacute;': 'Ý' },
  { '&THORN;': 'Þ' },
  { '&szlig;': 'ß' },
  { '&agrave;': 'à' },
  { '&aacute;': 'á' },
  { '&acirc;': 'â' },
  { '&atilde;': 'ã' },
  { '&auml;': 'ä' },
  { '&aring;': 'å' },
  { '&aelig;': 'æ' },
  { '&ccedil;': 'ç' },
  { '&egrave;': 'è' },
  { '&eacute;': 'é' },
  { '&ecirc;': 'ê' },
  { '&euml;': 'ë' },
  { '&igrave;': 'ì' },
  { '&iacute;': 'í' },
  { '&icirc;': 'î' },
  { '&iuml;': 'ï' },
  { '&eth;': 'ð' },
  { '&ntilde;': 'ñ' },
  { '&ograve;': 'ò' },
  { '&oacute;': 'ó' },
  { '&ocirc;': 'ô' },
  { '&otilde;': 'õ' },
  { '&ouml;': 'ö' },
  { '&divide;': '÷' },
  { '&oslash;': 'ø' },
  { '&ugrave;': 'ù' },
  { '&uacute;': 'ú' },
  { '&ucirc;': 'û' },
  { '&uuml;': 'ü' },
  { '&yacute;': 'ý' },
  { '&thorn;': 'þ' },
  { '&yuml;': 'ÿ' },
  { '&#035;': '#' },
  { '&#036;': '$' },
  { '&#037;': '%' },
  { '&#038;': '&' },
  { '&#039;': '\'' },
  { '&#040;': '(' },
  { '&#041;': ')' },
  { '&#042;': '*' },
  { '&#043;': '#ERROR!' },
  { '&#044;': ',' },
  { '&#045;': '-' },
  { '&#046;': '.' },
  { '&#047;': '/' },
  { '&#048;': '0' },
  { '&#049;': '1' },
  { '&#050;': '2' },
  { '&#051;': '3' },
  { '&#052;': '4' },
  { '&#053;': '5' },
  { '&#054;': '6' },
  { '&#055;': '7' },
  { '&#056;': '8' },
  { '&#057;': '9' },
  { '&#058;': ':' },
  { '&#059;': ';' },
  { '&#060;': '<' },
  { '&#061;': '#ERROR!' },
  { '&#062;': '>' },
  { '&#063;': '?' },
  { '&#064;': '@' },
  { '&#065;': 'A' },
  { '&#066;': 'B' },
  { '&#067;': 'C' },
  { '&#068;': 'D' },
  { '&#069;': 'E' },
  { '&#070;': 'F' },
  { '&#071;': 'G' },
  { '&#072;': 'H' },
  { '&#073;': 'I' },
  { '&#074;': 'J' },
  { '&#075;': 'K' },
  { '&#076;': 'L' },
  { '&#077;': 'M' },
  { '&#078;': 'N' },
  { '&#079;': 'O' },
  { '&#080;': 'P' },
  { '&#081;': 'Q' },
  { '&#082;': 'R' },
  { '&#083;': 'S' },
  { '&#084;': 'T' },
  { '&#085;': 'U' },
  { '&#086;': 'V' },
  { '&#087;': 'W' },
  { '&#088;': 'X' },
  { '&#089;': 'Y' },
  { '&#090;': 'Z' },
  { '&#091;': '[' },
  { '&#092;': '\\' },
  { '&#093;': ']' },
  { '&#094;': '^' },
  { '&#095;': '_' },
  { '&#096;': '`' },
  { '&#097;': 'a' },
  { '&#098;': 'b' },
  { '&#099;': 'c' },
  { '&#100;': 'd' },
  { '&#101;': 'e' },
  { '&#102;': 'f' },
  { '&#103;': 'g' },
  { '&#104;': 'h' },
  { '&#105;': 'i' },
  { '&#106;': 'j' },
  { '&#107;': 'k' },
  { '&#108;': 'l' },
  { '&#109;': 'm' },
  { '&#110;': 'n' },
  { '&#111;': 'o' },
  { '&#112;': 'p' },
  { '&#113;': 'q' },
  { '&#114;': 'r' },
  { '&#115;': 's' },
  { '&#116;': 't' },
  { '&#117;': 'u' },
  { '&#118;': 'v' },
  { '&#119;': 'w' },
  { '&#120;': 'x' },
  { '&#121;': 'y' },
  { '&#122;': 'z' },
  { '&#123;': '{' },
  { '&#124;': '|' },
  { '&#125;': '}' },
  { '&#126;': '~' },
  { '&#160;': ' ' },
  { '&#161;': '¡' },
  { '&#162;': '¢' },
  { '&#163;': '£' },
  { '&#164;': '¤' },
  { '&#165;': '¥' },
  { '&#166;': '¦' },
  { '&#167;': '§' },
  { '&#168;': '¨' },
  { '&#169;': '©' },
  { '&#170;': 'ª' },
  { '&#171;': '«' },
  { '&#172;': '¬' },
  { '&#173;': '­' },
  { '&#174;': '®' },
  { '&#175;': '¯' },
  { '&#176;': '°' },
  { '&#177;': '±' },
  { '&#178;': '²' },
  { '&#179;': '³' },
  { '&#180;': '´' },
  { '&#181;': 'µ' },
  { '&#182;': '¶' },
  { '&#183;': '·' },
  { '&#184;': '¸' },
  { '&#185;': '¹' },
  { '&#186;': 'º' },
  { '&#187;': '»' },
  { '&#188;': '¼' },
  { '&#189;': '½' },
  { '&#190;': '¾' },
  { '&#191;': '¿' },
  { '&#192;': 'À' },
  { '&#193;': 'Á' },
  { '&#194;': 'Â' },
  { '&#195;': 'Ã' },
  { '&#196;': 'Ä' },
  { '&#197;': 'Å' },
  { '&#198;': 'Æ' },
  { '&#199;': 'Ç' },
  { '&#200;': 'È' },
  { '&#201;': 'É' },
  { '&#202;': 'Ê' },
  { '&#203;': 'Ë' },
  { '&#204;': 'Ì' },
  { '&#205;': 'Í' },
  { '&#206;': 'Î' },
  { '&#207;': 'Ï' },
  { '&#208;': 'Ð' },
  { '&#209;': 'Ñ' },
  { '&#210;': 'Ò' },
  { '&#211;': 'Ó' },
  { '&#212;': 'Ô' },
  { '&#213;': 'Õ' },
  { '&#214;': 'Ö' },
  { '&#215;': '×' },
  { '&#216;': 'Ø' },
  { '&#217;': 'Ù' },
  { '&#218;': 'Ú' },
  { '&#219;': 'Û' },
  { '&#220;': 'Ü' },
  { '&#221;': 'Ý' },
  { '&#222;': 'Þ' },
  { '&#223;': 'ß' },
  { '&#224;': 'à' },
  { '&#225;': 'á' },
  { '&#226;': 'â' },
  { '&#227;': 'ã' },
  { '&#228;': 'ä' },
  { '&#229;': 'å' },
  { '&#230;': 'æ' },
  { '&#231;': 'ç' },
  { '&#232;': 'è' },
  { '&#233;': 'é' },
  { '&#234;': 'ê' },
  { '&#235;': 'ë' },
  { '&#236;': 'ì' },
  { '&#237;': 'í' },
  { '&#238;': 'î' },
  { '&#239;': 'ï' },
  { '&#240;': 'ð' },
  { '&#241;': 'ñ' },
  { '&#242;': 'ò' },
  { '&#243;': 'ó' },
  { '&#244;': 'ô' },
  { '&#245;': 'õ' },
  { '&#246;': 'ö' },
  { '&#247;': '÷' },
  { '&#248;': 'ø' },
  { '&#249;': 'ù' },
  { '&#250;': 'ú' },
  { '&#251;': 'û' },
  { '&#252;': 'ü' },
  { '&#253;': 'ý' },
  { '&#254;': 'þ' },
  { '&#255;': 'ÿ' },
];
